theme: Minima
title: Food Systems Research Group

# This goes into the footer:
author: the team

# Define the navigation links
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
#  - data.md
