theme: Minima
title: Food Systems Research Group

# This goes into the footer:
author: 
  name: Marco Springmann
  email: m.springmann@ucl.ac.uk 

# Define the navigation links
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - tools.md
#  - data.md

Minima:
  skin: dark
