theme: Minima
title: Food Systems Research Group

# This goes into the footer:
author: 
  name: Marco Springmann

# Define the navigation links
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
#  - data.md

minima:
  skin: auto
